version: '3.8'

services:

  icecast:
    image: moul/icecast
    container_name: ${CONTAINER_NAME_ICECAST:-radio_icecast}
    ports:
      - "${PORT_ICECAST:-8005}:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=${RADIO_PASS}
      - ICECAST_ADMIN_PASSWORD=${RADIO_ADMIN}
      - ICECAST_PASSWORD=${RADIO_PASS}
    restart: unless-stopped

  liquidsoap:
    build:
      context: .
      dockerfile: Dockerfile.liquidsoap
    container_name: ${CONTAINER_NAME_LIQ:-radio_liquidsoap}
    volumes:
      - /home/ubuntu/musica:/app/musica
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_PASS=${RADIO_PASS}
      - ICECAST_MOUNT=/radio.mp3
    command: liquidsoap /app/radio.liq
    depends_on:
      - icecast
    restart: unless-stopped

  autodj:
    build: .
    container_name: ${CONTAINER_NAME_AUTODJ:-radio_autodj}
    ports:
      - "${PORT_DASHBOARD:-5000}:5000"
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - LIQUIDSOAP_HOST=liquidsoap
      - LIQUIDSOAP_PORT=1234
      - STREAM_URL=${STREAM_URL}
    volumes:
      - /home/ubuntu/musica:/app/musica
    depends_on:
      - icecast
      - liquidsoap
    restart: unless-stopped
